version: '3.8'
services:
  observability-service:
    image: gurururu/observability-service:latest
    container_name: observability-service
    restart: unless-stopped
    network_mode: host
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://43.200.226.255:4318
      - OPENSEARCH_URL=https://vpc-log-platform-dev-a4ijq3cswvvdkbdaf677gkkvl4.ap-northeast-2.es.amazonaws.com
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Fkvk1234!
      - AMP_ENDPOINT=https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-d18e8248-cbac-4fd8-986c-2947a850932e/api/v1/query
      - ALLOWED_ORIGINS=http://localhost:3000
      - RDS_INSTANCE_IDENTIFIER=log-platform-dev-customer-postgres
      - AWS_REGION=ap-northeast-2