version: '3.8'
services:
  observability-service:
    image: gurururu/observability-service:latest
    container_name: observability-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://3.39.122.12:4318
      - OPENSEARCH_URL=https://vpc-log-platform-dev-emru3vfn6thqsybe5qc7nndgga.ap-northeast-2.es.amazonaws.com
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Fkvk1234!
      - AMP_ENDPOINT=https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-96fd8790-3be8-4cea-9d38-a6e33e720b89/api/v1/query
      - ALLOWED_ORIGINS=http://localhost:3000