version: '3.8'
services:
  observability-service:
    image: gurururu/observability-service:latest
    container_name: observability-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://52.79.67.130:4318
      - OPENSEARCH_URL=https://vpc-log-platform-dev-emru3vfn6thqsybe5qc7nndgga.ap-northeast-2.es.amazonaws.com
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Fkvk1234!
      - AMP_ENDPOINT=https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-d9c004f7-e588-4dbf-805d-b9690ee79dcd/api/v1/query
      - ALLOWED_ORIGINS=http://localhost:3000